#!/bin/bash

# just to test if the script is run...
touch foo.bar

cd OPENSENSE_sandbox_outsource_environment

echo ''
echo 'get content of submodules'
git submodule update --init

echo ''
echo 'done'

echo ''
echo 'Install RAINLINK'
cd RAINLINK
R CMD INSTALL RAINLINK*.tar.gz

echo ''
echo 'create dir in RAINLINK for figures'
mkdir Figures

# this must be the last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
